
spring:
  application:
    name: tlias-web-management

#配置数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: clannad98
  servlet:
    multipart:
#      最大单个文件大小
      max-file-size: 10MB
#      最大请求大小
      max-request-size: 50MB

#配置mybatis的日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    org.apache.tomcat: info

#阿里云Oss
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-xiaoyangoioioi
    region: cn-beijing



